"""
Neural network models based on oscillatory dynamics.

This module provides various implementations of neural networks
based on oscillatory dynamics and ODEs.
"""

from .config import (
    OscillatoryAutoencoderConfig,
    PatchOscillatoryAutoencoderConfig,
    FeedForwardPatchAutoencoderConfig,
    ConvLSTMPatchDenoiserConfig,
    RecurrentConvPatchDenoiserConfig,
    RecurrentConvPriorRefinementPatchDenoiserConfig,
    KuramotoImageGeneratorConfig,
    WaveletAutoencoderConfig,
    WinfreeCoarseGlobalRatePhaseConditionalPatchDenoiserConfig,
    WinfreeCoarsePredictiveRatePhaseConditionalPatchDenoiserConfig,
    WinfreeCoarseRatePhaseConditionalPatchDenoiserConfig,
    WinfreeFieldAutoencoderConfig,
    WinfreeConditionalPatchDenoiserConfig,
    WinfreeGlobalRatePhaseConditionalPatchDenoiserConfig,
    WinfreePriorRefinementPatchDenoiserConfig,
    WinfreeRatePhaseConditionalPatchDenoiserConfig,
    WinfreePatchAutoencoderConfig,
    WinfreePhaseAutoencoderConfig,
)
from .fractal import FractalHORNCell
from .generative import (
    HORNImageGenerator,
    KuramotoImageGenerator,
    KuramotoPhaseVAE,
    StateMLPImageGenerator,
)
from .jepa import (
    ConvLSTMPatchJEPAPredictor,
    FeedForwardPatchJEPAPredictor,
    RecurrentConvPatchJEPAPredictor,
    WinfreeGlobalRatePhasePatchJEPAPredictor,
    WinfreeRatePhasePatchJEPAPredictor,
)
from .oscillatory import (
    AmplitudeVelocityAutoencoder,
    AmplitudeVelocityDecoder,
    AmplitudeVelocityEncoder,
    AmplitudeVelocityHORN,
    AmplitudeVelocityHORNCell,
    AmplitudeVelocityOscillatorCell,
    AutoregressiveOscillatoryDecoder,
    ConvLSTMPatchDenoiser,
    FeedForwardPatchAutoencoder,
    OscillatorState,
    OscillatoryAutoencoder,
    OscillatoryEncoder,
    OscillatorySequenceLayer,
    PatchOscillatoryAutoencoder,
    PositionalLatentOscillatoryDecoder,
    RecurrentConvPatchDenoiser,
    RecurrentConvPriorRefinementPatchDenoiser,
    RepeatedLatentOscillatoryDecoder,
)
from .phase import (
    WinfreePhaseAutoencoder,
    WinfreePhaseOscillatorCell,
    WinfreePhaseSequenceLayer,
)
from .phase_flow import (
    CoarseGlobalPhaseRateFlowField,
    PhaseRateFlowField,
    RecurrentConvFlowField,
)
from .wavelet import (
    ProductionWaveletAutoencoder,
    WaveletOscillatorCell,
    WaveletOscillatoryAutoencoder,
)
from .winfree import (
    WONNPatchAutoencoder,
    WinfreeCoarseGlobalRatePhaseConditionalPatchDenoiser,
    WinfreeCoarsePredictiveRatePhaseConditionalPatchDenoiser,
    WinfreeCoarseRatePhaseConditionalPatchDenoiser,
    WinfreeConditionalPatchDenoiser,
    WinfreeFieldAutoencoder,
    WinfreeFieldDecoder,
    WinfreeFieldEncoder,
    WinfreeFieldLayer,
    WinfreeGlobalRatePhaseConditionalPatchDenoiser,
    WinfreePatchAutoencoder,
    WinfreePriorRefinementPatchDenoiser,
    WinfreeRatePhaseConditionalPatchDenoiser,
    phase_features,
    wrap_phase,
)

__all__ = [
    "OscillatorState",
    "AmplitudeVelocityOscillatorCell",
    "OscillatorySequenceLayer",
    "OscillatoryEncoder",
    "RepeatedLatentOscillatoryDecoder",
    "PositionalLatentOscillatoryDecoder",
    "AutoregressiveOscillatoryDecoder",
    "OscillatoryAutoencoder",
    "PatchOscillatoryAutoencoder",
    "FeedForwardPatchAutoencoder",
    "RecurrentConvPatchDenoiser",
    "RecurrentConvPriorRefinementPatchDenoiser",
    "ConvLSTMPatchDenoiser",
    "AmplitudeVelocityHORNCell",
    "AmplitudeVelocityHORN",
    "AmplitudeVelocityEncoder",
    "AmplitudeVelocityDecoder",
    "AmplitudeVelocityAutoencoder",
    "WaveletOscillatorCell",
    "WaveletOscillatoryAutoencoder",
    "ProductionWaveletAutoencoder",
    "OscillatoryAutoencoderConfig",
    "PatchOscillatoryAutoencoderConfig",
    "FeedForwardPatchAutoencoderConfig",
    "RecurrentConvPatchDenoiserConfig",
    "RecurrentConvPriorRefinementPatchDenoiserConfig",
    "KuramotoImageGeneratorConfig",
    "KuramotoPhaseVAE",
    "ConvLSTMPatchDenoiserConfig",
    "WaveletAutoencoderConfig",
    "WinfreeCoarseGlobalRatePhaseConditionalPatchDenoiserConfig",
    "WinfreeCoarsePredictiveRatePhaseConditionalPatchDenoiserConfig",
    "WinfreeCoarseRatePhaseConditionalPatchDenoiserConfig",
    "WinfreePhaseAutoencoderConfig",
    "WinfreeFieldAutoencoderConfig",
    "WinfreeConditionalPatchDenoiserConfig",
    "WinfreeGlobalRatePhaseConditionalPatchDenoiserConfig",
    "WinfreePriorRefinementPatchDenoiserConfig",
    "WinfreeRatePhaseConditionalPatchDenoiserConfig",
    "WinfreePatchAutoencoderConfig",
    "WinfreePhaseOscillatorCell",
    "WinfreePhaseSequenceLayer",
    "WinfreePhaseAutoencoder",
    "PhaseRateFlowField",
    "CoarseGlobalPhaseRateFlowField",
    "RecurrentConvFlowField",
    "wrap_phase",
    "phase_features",
    "WinfreeFieldLayer",
    "WinfreeFieldEncoder",
    "WinfreeFieldDecoder",
    "WinfreeFieldAutoencoder",
    "WinfreePatchAutoencoder",
    "WinfreeConditionalPatchDenoiser",
    "WinfreeRatePhaseConditionalPatchDenoiser",
    "WinfreeGlobalRatePhaseConditionalPatchDenoiser",
    "WinfreeCoarseGlobalRatePhaseConditionalPatchDenoiser",
    "WinfreeCoarsePredictiveRatePhaseConditionalPatchDenoiser",
    "WinfreeCoarseRatePhaseConditionalPatchDenoiser",
    "WinfreePriorRefinementPatchDenoiser",
    "WONNPatchAutoencoder",
    "FractalHORNCell",
    "HORNImageGenerator",
    "KuramotoImageGenerator",
    "FeedForwardPatchJEPAPredictor",
    "RecurrentConvPatchJEPAPredictor",
    "ConvLSTMPatchJEPAPredictor",
    "WinfreeRatePhasePatchJEPAPredictor",
    "WinfreeGlobalRatePhasePatchJEPAPredictor",
]
